export const AppModules = {
    HOME: "Home",
    PRODUCT: "product",
    BRAND: "brand",
    CATEGORY: "category",
    VARIATION: "variation",
    UNITS: "Units",
    TAXES: "Taxes",
    PANDEL: "pandel",
    PURCHASE: "purchase",
    PURCHASE_RETURN: "purchase_return",
    CITY: "city",
    COUNTRY: "country",
    ZONE: "zone",
    POS: "POS",
    DISCOUNT: "discount",
    CURRENCY: "currency",
    COUPON: "coupon",
    EXPENSE_ADMIN: "expenseAdmin",
    EXPENSE_CATEGORY: "expense_category",
    REVENUE: "Revenue",
    TRANSFER: "transfer",
    CASHIER_SHIFT_REPORT: "cashier_shift_report",
    FINANCIAL_ACCOUNT: "financial_account",
    PAYMENT_METHOD: "payment_method",
    PAYMENT: "payment",
    ADMIN: "Admin",
    SUPPLIER: "Supplier",
    CUSTOMER: "customer",
    CUSTOMER_GROUP: "customer_group",
    CASHIER: "cashier",
    PERMISSION: "permission",
    POPUP: "popup",
    POINT: "point",
    REDEEM_POINTS: "redeem_points",
    MANUFACTURING_LIST: "manufacturing",
    WAREHOUSE: "warehouse",
    PRODUCT_WAREHOUSE: "product_warehouse",
    ORDERS_REPORT: "orders_report",
};

export const ModuleActions = {
    VIEW: "view",
    ADD: "add",
    EDIT: "edit",
    DELETE: "delete",
};
